services:
  - type: web
    name: doctor-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
      - key: DOCTOR_TELEGRAM_ID
        value: ${DOCTOR_TELEGRAM_ID}
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: WEBHOOK_URL
        value: ${WEBHOOK_URL}
